# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c
sudo: required
dist: trusty

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-knitr r-cran-rmarkdown r-cran-lme4 r-cran-arm
  - ./run.sh install_aptget r-cran-testthat r-cran-future.apply r-cran-broom.mixed
  - ./run.sh install_aptget r-cran-rstanarm r-cran-amelia r-cran-dt
  - ./run.sh install_aptget r-cran-dplyr r-cran-mvtnorm r-cran-foreach
  - ./run.sh install_aptget r-cran-shiny r-cran-abind r-cran-ggplot2
  - ./run.sh install_r blme

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

after_success:
  - travis_wait Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only: master

